
package org.apache.axis2.sample.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JAXWSService", targetNamespace = "http//axis2.apache.org/sample/jaxws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JAXWSService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoString", targetNamespace = "http//axis2.apache.org/sample/jaxws", className = "org.apache.axis2.sample.jaxws.EchoString")
    @ResponseWrapper(localName = "echoStringResponse", targetNamespace = "http//axis2.apache.org/sample/jaxws", className = "org.apache.axis2.sample.jaxws.EchoStringResponse")
    public String echoString(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.apache.axis2.sample.jaxws.Project
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoProject", targetNamespace = "http//axis2.apache.org/sample/jaxws", className = "org.apache.axis2.sample.jaxws.EchoProject")
    @ResponseWrapper(localName = "echoProjectResponse", targetNamespace = "http//axis2.apache.org/sample/jaxws", className = "org.apache.axis2.sample.jaxws.EchoProjectResponse")
    public Project echoProject(
            @WebParam(name = "arg0", targetNamespace = "")
            Project arg0);

}
